# Generated by Django 4.2.5 on 2023-10-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_alter_product_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=600),
        ),
    ]
